# Build stage
FROM gradle:8.5.0-jdk17 AS build
WORKDIR /workspace
COPY --chown=gradle:gradle .. .
RUN gradle :api-gateway:bootJar -x test

# Run stage
FROM amazoncorretto:17-alpine-jdk
WORKDIR /app
COPY --from=build /workspace/api-gateway/build/libs/*.jar app.jar
EXPOSE ${API_GATEWAY_PORT}
ENTRYPOINT ["java", "-jar", "app.jar"]