# Build stage
FROM gradle:8.5.0-jdk17 AS build
WORKDIR /workspace
COPY --chown=gradle:gradle .. .
RUN gradle :banks-service:bootJar -x test

# Run stage
FROM amazoncorretto:17-alpine-jdk
WORKDIR /app
COPY --from=build /workspace/banks-service/build/libs/*.jar app.jar
EXPOSE ${BANKS_SERVICE_PORT}
ENTRYPOINT ["java", "-jar", "app.jar"]